fix: 🐛 add dependabot yml
casechek/aws-cdk-elasticsearch-index pull request #104
Opened 2021-05-27 12:01 UTC by anafaggiano

- Adds dependabot for docker npm and github actions

2021-05-27 14:25 UTC, andrewdhazlett requested changes
please also disable renovate

2021-05-27 14:51 UTC, nalhabash approved these changes

2021-05-27 15:01 UTC, robaone approved these changes

2021-05-28 15:19 UTC, andrewdhazlett approved these changes

2021-05-28 15:34 UTC, merged